Repository ACCESS-Cloud-Based-InSAR/dem-stitcher, pull requests merged in 2022-03, with the labels that each got.

#10 Fix typo in readme
  README.md
Labels: bumpless

#15 Release 2.0.1
  .github/queries/associated-pr.query.yml
  .github/queries/pr-labels.query.yml
  .github/workflows/changelog.yml
  .github/workflows/distribute.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/tag.yml
  .github/workflows/test-and-tag.yml
  .github/workflows/test.yml
  CHANGELOG.md
  MANIFEST.in
  README.md
  dem_stitcher/stitcher.py
  environment.yml
  setup.py
  tests/test_stitcher.py
Labels: patch

#19 fix including package data
  CHANGELOG.md
  setup.py
Labels: bug

#21 Fix linting with flake8
  dem_stitcher/geoid.py
  dem_stitcher/rio_tools.py
  dem_stitcher/stitcher.py
  environment.yml
  setup.py
Labels: bumpless

#26 Style fixes for flake8 linting
  dem_stitcher/geoid.py
  dem_stitcher/stitcher.py
Labels: bumpless

#25 Release v2.1.0
  CHANGELOG.md
  dem_stitcher/geoid.py
  dem_stitcher/rio_tools.py
  dem_stitcher/stitcher.py
  environment.yml
  setup.py
  tests/test_stitcher.py
Labels: minor
