Repository ACCESS-Cloud-Based-InSAR/dem-stitcher, pull requests merged in 2022-07, with the labels that each got.

#35 Adding Glo-90
  .gitignore
  CHANGELOG.md
  README.md
  dem_stitcher/data/glo_30.geojson.zip
  dem_stitcher/data/glo_90.geojson.zip
  dem_stitcher/data/glo_90_missing.geojson.zip
  dem_stitcher/dem_readers.py
  dem_stitcher/exceptions.py
  dem_stitcher/glo_30_missing.py
  dem_stitcher/rio_tools.py
  dem_stitcher/stitcher.py
  notebooks/Filling_in_missing_glo-30_tiles_with_glo-90_tiles.ipynb
  notebooks/organize_tile_data/0_Format_and_Organize_Data.ipynb
  notebooks/organize_tile_data/1_Missing_glo-30_tiles.ipynb
  notebooks/organize_tile_data/Format_and_Organize_Data.ipynb
  tests/data/missing/glo_30_left.tif
  tests/data/missing/glo_90_right.tif
  tests/data/missing/glo_merged.tif
  tests/test_exceptions.py
  tests/test_missing.py
  tests/test_stitcher.py
Labels: patch

#37 Acknowledgements
  README.md
  setup.py
Labels: documentation, bumpless

#42 Tweak my name
  README.md
  setup.py
Labels: documentation, bumpless

#41 Add Python 3.10 back
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  environment.yml
  setup.py
Labels: patch, CI/CD

#43 Some tweaks to the README for conda-forge
  README.md
Labels: documentation, bumpless

#45 Fix changelog
  CHANGELOG.md
Labels: bumpless

#46 v2.3.0
  .github/workflows/test.yml
  .gitignore
  CHANGELOG.md
  README.md
  dem_stitcher/data/glo_30.geojson.zip
  dem_stitcher/data/glo_90.geojson.zip
  dem_stitcher/data/glo_90_missing.geojson.zip
  dem_stitcher/dem_readers.py
  dem_stitcher/exceptions.py
  dem_stitcher/glo_30_missing.py
  dem_stitcher/rio_tools.py
  dem_stitcher/stitcher.py
  environment.yml
  notebooks/Filling_in_missing_glo-30_tiles_with_glo-90_tiles.ipynb
  notebooks/organize_tile_data/0_Format_and_Organize_Data.ipynb
  notebooks/organize_tile_data/1_Missing_glo-30_tiles.ipynb
  notebooks/organize_tile_data/Format_and_Organize_Data.ipynb
  setup.py
  tests/data/missing/glo_30_left.tif
  tests/data/missing/glo_90_right.tif
  tests/data/missing/glo_merged.tif
  tests/test_exceptions.py
  tests/test_missing.py
  tests/test_stitcher.py
Labels: minor

#39 Conda forge
  README.md
  environment.yml
Labels: documentation, bumpless
